### ISSUE TITLE
Opening a table in platybrowser fails

### ISSUE THREAD

**Issue by constantinpape** [tischi/table-utils#9]
I can build the platybrowser with the local `table-utils` now.
However, when I try to open a table, it fails with the following exception:

```
Exception in thread "AWT-EventQueue-1" java.lang.NoClassDefFoundError: de/embl/cba/lazyalgorithm/RandomAccessibleIntervalFilter
	at de.embl.cba.tables.view.combined.SegmentsTableBdvAnd3dViews.show(SegmentsTableBdvAnd3dViews.java:60)
	at de.embl.cba.tables.view.combined.SegmentsTableBdvAnd3dViews.<init>(SegmentsTableBdvAnd3dViews.java:46)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.showAnnotatedLabelsSource(PlatyBrowserSourcesPanel.java:476)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.addSourceToViewer(PlatyBrowserSourcesPanel.java:392)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.addSourceToPanelAndViewer(PlatyBrowserSourcesPanel.java:376)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserSourcesPanel.addSourceToPanelAndViewer(PlatyBrowserSourcesPanel.java:333)
	at de.embl.cba.platynereis.platybrowser.PlatyBrowserActionPanel.lambda$null$4(PlatyBrowserActionPanel.java:391)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: de.embl.cba.lazyalgorithm.RandomAccessibleIntervalFilter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 22 more
```

**Comment by tischi** [comment]
Could you put this dependency with this version into the pom?
```
		<dependency>
			<groupId>de.embl.cba</groupId>
			<artifactId>imglib2-lazy-algorithm</artifactId>
			<version>0.2.2</version>
		</dependency>
```
Does that help?

**Comment by constantinpape** [comment]
Yes, that fixed it thanks!
Should I make a PR to add it?

**Comment by tischi** [comment]
not worth it since I will merge all those repos soon anyway.

**Comment by constantinpape** [comment]
ok, I have a bigger WIP PR coming anyways
